### PR TITLE
Implemented `.finally(fn)`, fixing #25

### PR DESCRIPTION
**Pull request by Kaelinator**
I am not completely sure if this is implemented correctly. Personally, I have never used `.finally`, but I read up on its functionality, and have replicated the behavior.
Also, I'm debating whether or not I should merge `impl-finally` with my master branch...

### CODE REVIEW

**Comment by Kaelinator** [comment]
This is awkward, the commits on #13 are showing up here...

**Comment by justsml** [comment]
Thanks @Kaelinator 

I've been thinking about `.finally()` being added to the Promise spec. I'm not sure I like how it's supposed to work. Kinda makes my techniques harder to reason about. I need more experience with it before I firm up my opinion however.

That said... I'm trying to emphasize that `functional-promises` is NOT itself a promises replacement. 

Adding every feature from Promises into the FP API muddles the message.

**Comment by justsml** [comment]
As for the mix of commit history, this happens 100% of the time on 2nd commits. (and sometimes I forget this key step) ;)

You need to pull from the upstream master, merge it into your local `master` - then create the new branch.

The key is to `checkout` the upstream master branch, then create the new branch to work on.

If you do it out of order, it's often easier to start a fresh branch and manually copy desired changes back in.

**Comment by justsml** [comment]
Ping me on slack if you need some help with the commands... 

Let me know if you want to do a pair programming session in the evening this or next week - I need a 2nd set of eyes - been working on a strange bug. 🤔

**Comment by justsml** [comment]
Closing for the moment, putting feature on backlog...

**Pull request closed without merging**
